### ISSUE TITLE
Add `write_metadata` function

### ISSUE THREAD

**Issue by MattBuckley-TfN** [Transport-for-the-North/caf.toolkit#124]
Create new function in `log_helpers` for writing model metadata to a YAML file, should be given `ToolDetails` and any metadata arguments.

`SystemInformation.load()` should be used to output that information to the YAML file.

Example of the function signature below, where metadata keyword arguments can be anything which can output to a YAML file e.g. standard Python types including int, str, float, dict, list ...

```python
def write_metadata(path: pathlib.Path, details: ToolDetails, **metadata: Any) -> None:
```

Example of the output file:

```yaml
# Tool details provided by function caller
tool_details:
  name: caf.toolkit
  version: 0.1.0
  homepage: https://caftoolkit.readthedocs.io/en/stable/
  source_url: https://github.com/Transport-for-the-North/caf.toolkit

# System information automatically determined using SystemInformation.load
system_information:
  user: PC User Name
  pc_name: Name of PC running
  python_version: 3.12
  operating_system: Windows 10
  architecture: AMD64
  processor: Intel
  cpu_count: 4
  total_ram: 100

# All the keyword arguments passed to the function
metadata:
  key: value
  date: 2024-06-19
  project: Project Name
  owner: Owner's name
  stakeholders:
    - Stakeholder 1
    - Stakeholder 2
    - Stakeholder 3
  inputs_folder: Path/to/inputs
```
